logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        SQL: DEBUG

datasource:
  username: root
  password: 12341234
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/project1